### ISSUE TITLE
[ADMIN] When deleting a row in add rooms/add moderatorss

### ISSUE THREAD

**Issue by BToo-V** [SOFENGG-T1AY1617/S18B-Team-Rofi#11]
![image](https://cloud.githubusercontent.com/assets/18240649/20244860/b210a390-a9cc-11e6-8208-8affb5e638b0.png)

When you click Add Rooms
Pop up appears showing input for rooms
Click add another room to make it 2 rows
Click the X in the first row
Now only one row left
Click the X in the first row again
Error

**Comment by bensonpoli** [comment]
Fixed by updating the predefined value of each the delete buttons every time the deleteRow method is called.
