### ISSUE TITLE
[FUNCTIONALITY] I can add duplicate admins

### ISSUE THREAD

**Issue by digora** [SOFENGG-T1AY1617/S18B-Team-Rofi#23]
1. Login with superuser account
james.sy@dlsu.edu.ph
password

2. Go to Account Management

3. Click Add Admins

4. Enter in the Add Admins Modal:
![image](https://cloud.githubusercontent.com/assets/17010016/20342753/a3a5ee76-ac26-11e6-8eeb-0f6208a56caf.png)

5. Click Confirm

**Comment by digora** [comment]
Expected Output not met. When I try to add a duplicate admin the message is "Success No admins were added." when trying to add a duplicate admin is not a "success" but a failure

**Comment by digora** [comment]
![wrongchoiceofwords](https://cloud.githubusercontent.com/assets/17010016/20392333/56b978f2-ad12-11e6-80e1-f0d1fce7ac34.gif)

**Comment by digora** [comment]
I can suggest that the message be "Error admin already exists" and change the color to red

**Comment by digora** [comment]
Don't close the modal kapag kulang yung department

**Comment by Tobska** [comment]
Fixed in latest pushes
![image](https://cloud.githubusercontent.com/assets/17682109/20393977/e3ceadba-ad18-11e6-8d5e-981df7676c8d.png)
