### ISSUE TITLE
I cannot add rooms after pressing cancel in edit rooms

### ISSUE THREAD

**Issue by rickng17** [SOFENGG-T1AY1617/S18B-Team-Rofi#27]
1. login using james.sy@dlsu.edu.ph
2. go to application settings
3. go to manage areas
4. click edit rooms in gokongwei hall
5. click cancel
6. click add rooms in gokongwei hall
7. input G302A as room name
8. input 3 as number of PCs
9. click confirm

![d](https://cloud.githubusercontent.com/assets/18289934/20391655/4cf3cf64-ad0f-11e6-9483-de2a23123cac.gif)

**Comment by bensonpoli** [comment]
@Dionne did minor fix by adding refresh button.

I found that the main cause of the bug, the bug is the "name" not being saved after retrieve initial data.
We will fix it once major bugs are fixed. 

![image](https://cloud.githubusercontent.com/assets/17338260/20395571/6471b278-ad1e-11e6-9778-64377699a77c.png)

**Comment by bensonpoli** [comment]
Reloading made it worst hahaha

**Comment by digora** [comment]
Possible solutions thought of so far:
1. Refreshing the page after cancel
2. Restricting a person to only edit one panel at a time

**Comment by psionic-nerd** [comment]
restriction to editing 1 panel + saving initial button html should fix this. (pushed to admin fixes branch)

**Comment by rickng17** [comment]
![j](https://cloud.githubusercontent.com/assets/18289934/20857983/f8e8cf60-b974-11e6-89c6-6d85d3b59860.gif)

commit  0c9a8bd032df2cce6a65f4d9629653e7b24e602f [0c9a8bd]

**Comment by psionic-nerd** [comment]
fixed?

![bug3](https://cloud.githubusercontent.com/assets/17312615/20866103/113985e2-ba5f-11e6-9708-cdd66502407b.gif)
