### ISSUE TITLE
When I try to edit multiple buildings at the same time, the rooms are temporarily copied to the other building.

### ISSUE THREAD

**Issue by RalphGanal** [SOFENGG-T1AY1617/S18B-Team-Rofi#28]
![bug](https://cloud.githubusercontent.com/assets/17705529/20393183/d38ae94e-ad15-11e6-8174-ed7e6efec866.gif)

1. Enter Admin Credentials “james.sy@dlsu.edu.ph” and “password”
2. Click Login
3. Click Application Settings
4. Click Manage Areas
5. Click Edit Rooms under Saint Joseph Hall
6. Click Edit Rooms under Henry Sy Sr. Hall
7. Click Cancel under Saint Joseph Hall

Rooms return to normal upon refresh

Might be that the cancel feature reverts using Henry Sy values instead of values from Saint Joseph Hall.

**Comment by bensonpoli** [comment]
Dionne made temporary fix with reload.

We will further fix it once other major bugs are solved.

**Comment by psionic-nerd** [comment]
Solution: added code to prevent users from editing 2 buildings at once in admin fixes branch
