### ISSUE TITLE
When I try to input a decimal number as the number of PCs in an area, the program accepts it.

### ISSUE THREAD

**Issue by RalphGanal** [SOFENGG-T1AY1617/S18B-Team-Rofi#29]
![bug](https://cloud.githubusercontent.com/assets/17705529/20394060/2cf86760-ad19-11e6-9fdd-07fef566a776.gif)

1. Enter Admin Credentials “james.sy@dlsu.edu.ph” and “password”
2. Click Login
3. Click Application Settings
4. Click Manage Areas
5. Click Edit Rooms under Gokongwei
6. Append two "."s to the text
7. Move cursor between the two "."s
8. Press "7"
9. Press Delete
10. Click Save

**Comment by Tobska** [comment]
But the float value becomes an integer when changes are committed?

**Comment by digora** [comment]
Ralph input this in the test cases as well
