### ISSUE TITLE
I cannot go back to viewing the list of rooms of a building when I click edit rooms then press an X button then press cancel

### ISSUE THREAD

**Issue by rickng17** [SOFENGG-T1AY1617/S18B-Team-Rofi#31]
![g](https://cloud.githubusercontent.com/assets/18289934/20398401/450d85a6-ad28-11e6-999b-01fa9df0c015.gif)

**Comment by Tobska** [comment]
Temporarily resolved by reloading page (UX wise: not good 👎)

**Comment by psionic-nerd** [comment]
Cancel should be working now.
