### ISSUE TITLE
Just make the user input the first part of the email. Just have a text field for the earlier part and just make the rest "@dlsu.edu.ph" 

### ISSUE THREAD

**Issue by digora** [SOFENGG-T1AY1617/S18B-Team-Rofi#37]
For example

____________  @dlsu.edu.ph yung field ng email sa step 2

**Comment by Tobska** [comment]
there are also emails that still exist that ends with "delasalle.ph". Probably we could make a dropdown for the two emails.

**Comment by digora** [comment]
noted.
