### ISSUE TITLE
Add "Sorry no slots are available" or a message similar to that when there are no slots.

### ISSUE THREAD

**Issue by digora** [SOFENGG-T1AY1617/S18B-Team-Rofi#38]
For example, if the user is accessing the application past 9pm that means there will be no more available slots for today so instead of showing nothing in the slots part, just put "Sorry no slots are available" to avoid confusion,

**Comment by BToo-V** [comment]
Pushed, please check during 8PM

**Comment by digora** [comment]
Tested while on 
Commit ID: 22eb9a39ce71917577e4c3c83813aad909cc2517 [22eb9a3]
Imported new DB with stored procedures. 

Results where less than desired
![timenotresolved](https://cloud.githubusercontent.com/assets/17010016/20544846/f70e8dbe-b146-11e6-96fd-aceca121a578.gif)

Console did not display any error message.

**Comment by digora** [comment]
![image](https://cloud.githubusercontent.com/assets/17010016/20548984/12177280-b163-11e6-890c-4b5d5d31e205.png)

Set the time of the server to Puerto Rico to test this. As of writing this report, the time of Puerto Rico is around 9:50 pm and I see no message.

![image](https://cloud.githubusercontent.com/assets/17010016/20548991/357b3356-b163-11e6-9a02-a210a8da0852.png)
