### ISSUE TITLE
I want to be able to see only the admins and not the moderators, as a super admin.

### ISSUE THREAD

**Issue by digora** [SOFENGG-T1AY1617/S18B-Team-Rofi#39]
During an interview with Sir James Sy he told us that he did not care for the list of moderators.

To see the mistake:
Access the admin ui of the project
Click Account Management

![image](https://cloud.githubusercontent.com/assets/17010016/20589937/a397460c-b25a-11e6-89bf-464c6e8a52e4.png)

You can see that there is a List of Moderators in the Account Management tab.
Remove it.

**Comment by psionic-nerd** [comment]
super user views have been created to separate the actions of the admin & super user
